/*
 * Copyright 2025-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package rife.bld.extension.junitreporter;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import rife.bld.extension.tools.IOTools;

import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;
import java.util.regex.Pattern;
import java.util.stream.IntStream;

/**
 * Utility class for parsing JUnit XML test reports.
 * <p>
 * Extracts test failure and error details from JUnit XML files generated by Maven Surefire,
 * Gradle, or similar test runners. Groups results by class name and supports display names
 * from {@code system-out} elements.
 * <p>
 * This parser is intended for local, trusted XML files. Basic XXE protection is enabled,
 * but full hardening is unnecessary for typical build tool output.
 *
 * @author <a href="https://erik.thauvin.net/">Erik C. Thauvin</a>
 * @since 1.0
 */
public final class JUnitXmlParser {

    /**
     * XML attribute name for failure messages.
     */
    public static final String MESSAGE_ATTR = "message";
    /**
     * XML attribute name for test case names.
     */
    public static final String NAME_ATTR = "name";
    /**
     * XML tag name for test case elements.
     */
    public static final String TESTCASE_TAG = "testcase";
    private static final String CLASSNAME_ATTR = "classname";
    private static final String DEFAULT_MESSAGE = "No message provided";
    private static final Pattern DISPLAY_NAME_PATTERN = Pattern.compile("display-name:\\s*([^\\r\\n]+)");
    private static final String ERROR_TAG = "error";
    private static final String FAILURE_TAG = "failure";
    private static final String SYSTEM_OUT_TAG = "system-out";
    private static final String TIME_ATTR = "time";
    private static final String TYPE_ATTR = "type";

    private JUnitXmlParser() {
        // Prevent instantiation
    }

    /**
     * Creates a secure {@link DocumentBuilderFactory} with basic XXE protection.
     * <p>
     * Enables {@link XMLConstants#FEATURE_SECURE_PROCESSING} and disallows DOCTYPE declarations
     * to prevent XXE attacks. Sufficient for parsing trusted JUnit reports.
     *
     * @return a configured factory instance
     * @throws ParserConfigurationException if the parser cannot be configured securely
     */
    private static DocumentBuilderFactory createSecureFactory() throws ParserConfigurationException {
        var factory = DocumentBuilderFactory.newInstance();
        factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
        factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
        return factory;
    }

    /**
     * Creates a {@link TestFailure} from a test case and failure element.
     * <p>
     * Extracts test name, class name, execution time, display name, failure type, message,
     * and stack trace. Uses the provided default type if the failure element lacks a type attribute.
     *
     * @param testCaseElement the {@code <testcase>} element
     * @param failureElement  the {@code <failure>} or {@code <error>} element
     * @param defaultType     the failure type to use if not specified in the element
     * @return a populated {@code TestFailure} instance
     */
    public static TestFailure createTestFailure(Element testCaseElement,
                                                Element failureElement,
                                                String defaultType) {
        var testName = testCaseElement.getAttribute(NAME_ATTR);
        var className = testCaseElement.getAttribute(CLASSNAME_ATTR);
        var time = parseTime(testCaseElement.getAttribute(TIME_ATTR));
        var displayName = extractDisplayName(testCaseElement);

        var failureType = getAttributeOrDefault(failureElement, TYPE_ATTR, defaultType);
        var failureMessage = getAttributeOrDefault(failureElement, MESSAGE_ATTR, DEFAULT_MESSAGE);
        var stackTrace = getTextContentTrimmed(failureElement);

        return new TestFailure(testName, displayName, className, failureType, failureMessage, stackTrace, time);
    }

    /**
     * Extracts the JUnit display name from a test case's {@code system-out} element.
     * <p>
     * Searches for {@code display-name: <name>} patterns in the system-out text content.
     * Returns an empty string if no display name is found.
     *
     * @param testCaseElement the {@code <testcase>} element to search within
     * @return the display name if present, otherwise an empty string
     */
    public static String extractDisplayName(Element testCaseElement) {
        var systemOutNodes = testCaseElement.getElementsByTagName(SYSTEM_OUT_TAG);

        for (int i = 0; i < systemOutNodes.getLength(); i++) {
            var systemOutElement = (Element) systemOutNodes.item(i);
            var content = getTextContentTrimmed(systemOutElement);

            var matcher = DISPLAY_NAME_PATTERN.matcher(content);
            if (matcher.find()) {
                return matcher.group(1).trim();
            }
        }

        return "";
    }

    /**
     * Parses a JUnit XML report and groups test failures by class name.
     * <p>
     * Reads the specified file, extracts all {@code <testcase>} elements containing
     * {@code <failure>} or {@code <error>} children, and groups them by the {@code classname} attribute.
     * Results are sorted by class name.
     *
     * @param xmlFilePath the path to the JUnit XML file
     * @return a sorted map of class names to {@link TestClassFailures} containing grouped failures
     * @throws NullPointerException    if {@code xmlFilePath} is null
     * @throws JUnitXmlParserException if the file does not exist, is not readable, or parsing fails
     */
    @SuppressFBWarnings({"PATH_TRAVERSAL_IN", "XXE_DOCUMENT", "EXS_EXCEPTION_SOFTENING_NO_CONSTRAINTS"})
    public static Map<String, TestClassFailures> extractTestFailuresGrouped(String xmlFilePath) {
        Objects.requireNonNull(xmlFilePath, "XML file path cannot be null");

        var path = Paths.get(xmlFilePath);
        validateFile(path);

        try {
            var factory = createSecureFactory();
            var builder = factory.newDocumentBuilder();
            var document = builder.parse(path.toFile());
            document.getDocumentElement().normalize();

            return parseTestCases(document.getElementsByTagName(TESTCASE_TAG));

        } catch (ParserConfigurationException | IOException | SAXException e) {
            throw new JUnitXmlParserException("Failed to parse XML file: " + xmlFilePath, e);
        }
    }

    /**
     * Returns an attribute value from an element, or a default if blank or missing.
     *
     * @param element       the XML element
     * @param attributeName the attribute name to retrieve
     * @param defaultValue  the value to return if the attribute is blank
     * @return the attribute value, or {@code defaultValue} if blank
     */
    public static String getAttributeOrDefault(Element element, String attributeName, String defaultValue) {
        var value = element.getAttribute(attributeName);
        return value.isBlank() ? defaultValue : value;
    }

    /**
     * Returns the trimmed text content of an element.
     *
     * @param element the XML element
     * @return the trimmed text content, or an empty string if null
     */
    public static String getTextContentTrimmed(Element element) {
        var text = element.getTextContent();
        return text != null ? text.trim() : "";
    }

    /**
     * Parses test case nodes and groups failures by class name.
     * <p>
     * Iterates through all {@code <testcase>} elements, extracts failures and errors,
     * and groups them into {@link TestClassFailures} instances. Results are sorted by class name,
     * and failures within each class are sorted by test name.
     *
     * @param testCases a {@link NodeList} of {@code <testcase>} elements
     * @return a sorted map of class names to grouped failures
     */
    public static Map<String, TestClassFailures> parseTestCases(NodeList testCases) {
        var groupedFailures = new TreeMap<String, TestClassFailures>();

        IntStream.range(0, testCases.getLength())
                .mapToObj(testCases::item)
                .map(Element.class::cast)
                .forEach(testCaseElement -> processTestCase(testCaseElement, groupedFailures));

        return groupedFailures; // sortFailures call removed
    }

    /**
     * Parses a time value from a string.
     * <p>
     * Converts the input to a double. Returns {@code 0.0} if the input is null, empty,
     * invalid, or not finite (NaN, Infinity).
     *
     * @param timeStr the time value as a string
     * @return the parsed time as a double, or {@code 0.0} if invalid
     */
    public static double parseTime(String timeStr) {
        if (timeStr == null || timeStr.isEmpty()) {
            return 0.0;
        }

        try {
            var parsedTime = Double.parseDouble(timeStr);
            return Double.isFinite(parsedTime) ? parsedTime : 0.0;
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }

    /**
     * Processes failure or error nodes within a test case.
     *
     * @param nodes           the {@link NodeList} of failure/error elements
     * @param testCaseElement the parent {@code <testcase>} element
     * @param groupedFailures the map to populate with failures
     * @param type            the failure type to use as default
     */
    private static void processFailureNodes(NodeList nodes,
                                            Element testCaseElement,
                                            Map<String, TestClassFailures> groupedFailures,
                                            String type) {
        IntStream.range(0, nodes.getLength())
                .mapToObj(nodes::item)
                .map(Element.class::cast)
                .map(failureElement -> createTestFailure(testCaseElement, failureElement, type))
                .forEach(failure -> groupedFailures
                        .computeIfAbsent(failure.className(), TestClassFailures::new)
                        .addFailure(failure));
    }

    /**
     * Processes a single test case element for failures and errors.
     *
     * @param testCaseElement the {@code <testcase>} element to process
     * @param groupedFailures the map to populate with failures
     */
    private static void processTestCase(Element testCaseElement,
                                        Map<String, TestClassFailures> groupedFailures) {
        var failures = testCaseElement.getElementsByTagName(FAILURE_TAG);
        if (failures.getLength() > 0) {
            processFailureNodes(failures, testCaseElement, groupedFailures, FAILURE_TAG);
        }

        var errors = testCaseElement.getElementsByTagName(ERROR_TAG);
        if (errors.getLength() > 0) {
            processFailureNodes(errors, testCaseElement, groupedFailures, ERROR_TAG);
        }
    }

    /**
     * Validates that a file exists and is readable.
     *
     * @param path the file path to validate
     * @throws JUnitXmlParserException if the file does not exist, is not readable, or cannot be accessed
     */
    @SuppressWarnings("PMD.ExceptionAsFlowControl")
    public static void validateFile(Path path) throws JUnitXmlParserException {
        try {
            if (IOTools.notExists(path)) {
                throw new JUnitXmlParserException("File does not exist: " + path);
            }
            if (!Files.isReadable(path)) {
                throw new JUnitXmlParserException("File is not readable: " + path);
            }
        } catch (SecurityException e) {
            throw new JUnitXmlParserException("Cannot access file: " + path, e);
        }
    }
}